language: python

python:
  - '2.7'

# build on trusty 14.04 to avoid bug with latex
dist: trusty
sudo: required

before_install:
- sudo apt-get -qq update
- sudo apt-get install python-pip
- sudo apt-get install python-dev
- sudo apt-get install libfreetype6-dev
- sudo apt-get install texlive texlive-lang-french texlive-latex-extra texlive-latex-recommended
- sudo apt-get install dvipng

install: "pip install -r requirements.txt"

script: ./build.sh

env:
  global:
  - GH_REF="github.com/vtexier/Geconomicus.git"
  - secure: vIRRJhe7W5gWArNm3J0jrEieACcYUeqisGgm69sENN0Uea++zOBINr6w5l/Jgg9P+u+I2L4hirSq089kN3TNUWcZVwHgDaI7whTfdqOGHR/Go0EFcWDj4EwtXEpZGSKJebYykPnOGs16WG6tz/RT4c4H81JflL7MXjRT30DXpkdV/Nhq0itJIMfAm1+SdlX69DCAy2gd+0dAgPjAdVDrWu1H5PAHAOBLcNn3k7RM/YvWgBndPdPHst5clKHDsdfdooj+1P8DJ13zya6z6O4H0WDKPE9i5tvtmiitO5ruPWwM7yUFa0Q+mwH5z+WIrdo5k8Wxywy6k1Edy4ppnHizYV5xKTvNZp0DyY1ASbkklWr61Ta/HrvDjD0F9zCk0B+HJ+Y7AYeU6fESlO/3BrhSY3VGg7jm9V9umbkixfLOJGXQMoSpasK8MXFFnTzYU6S1zmeWhdmqlYW+0j8kjgTnJkp9jlIB0Vmal4YHSLy6Ur2OiwX1f3pMlqQuIfHjp6CgC/Ec3CeLCWQOzMPttkd7/SCR5PsucFKLsYePHDtWdNxyfIMt3eLF58ZH7Qh87Ty/Jl8jGcKlv0eqWnClGUdSI5ugJH+1zS/6t8z5qKc09HYcG2COt50lbwzM2nIUn1LBNTL8M6KALLu+wKZuJzuqXUUwmjBcPOTSvK2R4dPL+40=

#before_deploy: ./build_release.sh

deploy:
  # deploy dev updates on github-pages
  - provider: script
    skip_cleanup: true
    script: ./deploy_github_pages.sh
    on:
      branch: dev
      python: '2.7'

#  # deploy zip releases on tags
#  - provider: releases
#    api_key:
#      secure: muTCTtKjhLZtLSNS+OZCMh0kcHoW2hdpQkkGlX53RELYrg91mF8KAsVGFWwGGxfJlp/N+nTrBIphyCeef62NNSsME6wPOFZlfUGYv8QupxGCt8+phzHGRBphKvReQca2S0KnWX0L07kdwmzV7gZia1WTkAcH6HnZOxPY1MYJ9YJTFK75aW+r4VZGsdv2g8PJdMbxJBC83fFanLJ6mqrWvv6umxwCXRnfvhFVUFXiRdh4b2YF8jTX+EJ5ZhbCPb41i1uppzqxpgeIHEQMCJvNNPIikkRXO8SugswtM4BvYqCBVl0tBd7vuQCRw5PGTduoKgPsN+1sF4J1aLYg9hfx/AoWg1RpbqUVzIM0O7GAI49e6WL/2mKq2cE9nF0izxibfWYMLfSsjHAGeR2S7UgN6/5BmVFAVErwkVZTaJt+Z8E63UcGncmBLKIlp/usj+0BuTT4rUBknqeFmi9SSWdxV7ux2AceBCcHa0mXsAf5BJD4R4c1R/YYnrVWrH9iScpsl8x97lgIZs9XCdmSrZ94O90BEJzAPhz9hFgp1ZQzt1RmZs6HtQZVe3agmJvCPzFZ4Yy9lLtbVNeez00vkmpcW4kTMoNpCHZ8y5oo5ASFhxy+En9NjPOAFUSernKEnF7rKmjBpFXXEU0gFTZsx1DOBbfVhh+JPRIoXjc2m0TjS68=
#    file: ./rst/build/geconomicus.zip
#    skip_cleanup: true
#    on:
#      repo: vtexier/Geconomicus
#      tags: true
#      python: '3.4'
