language: python

python:
  - '2.7'

# build on trusty 14.04 to avoid bug with latex
dist: trusty
sudo: required

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y python-pip
- sudo apt-get install -y python-dev
- sudo apt-get install -y libfreetype6-dev
- sudo apt-get install -y texlive texlive-lang-french texlive-latex-extra texlive-latex-recommended
- sudo apt-get install -y dvipng

install: "pip install -r requirements.txt"

script: ./build.sh

env:
  global:
  - GH_REF="github.com/vtexier/theorie-relative-de-la-monnaie.git"
  - secure: T3mqMZT1BcaniFctu/h+ETOfwojfzAcgyg8Mp3n7Jlc4fvXVc1CKjbioZ/zgTdNmdI8iY1X4Yn7FPcObXuRTD2CEDhHufdx9IAyoRvhpU22lks7ZwMFK4QL78cWrXRckkmnMv01FSBaWXGaowocGJIJCXhSGn5PmxmzpgYXAETIsXy3bGKsQNw16+cyd1Ln9MGn+RiPvG2B+FsNx33TZb/gIQfQnyxAnHWDFBVK7AkFnxPG43yLWmWD3x2ECfxb12AEmNUqeM0HHp2HAX3S7NQH8iII7gSplGk6yX/WooOOmP3adiWDxOJ8c3Qtkxsd4cLeYtzU1upqvN20j4z6eJ+tYp9qplEjpcFU6P19y1uxw/+MeMG1jtWxHUyfNBF5U3y7nArD46TPmDTZTyaC1+JTssRFxFZeeTGXbyKapha1ceFlC6TMUtGz65km6c+P29mUkZEttOBM/6/ui3V2ugzrIiINuFBpoBwDMgRKK6EYhGijdrW8oQ79GsjY1nY8+mg3jbHO4TbsHVGPJXoGGtEwJYBq8H/mMRigWFrxAdCjZI5EWwT70V1oMiiarDPjfRP806L9cuKmITzQ40l1kTFVtloylPpLgfLXTKxMj2/9kPjROuvQGP9ieSbg/2NvwVNUC0aGUJ0fDZsCmvkrze1VZqEVCaha5M9rRblPiGPk=

#before_deploy: ./build_release.sh

deploy:
  # deploy dev updates on github-pages
  - provider: script
    skip_cleanup: true
    script: ./deploy_github_pages.sh
    on:
      branch: dev
      python: '2.7'

#  # deploy zip releases on tags
#  - provider: releases
#    api_key:
#      secure: muTCTtKjhLZtLSNS+OZCMh0kcHoW2hdpQkkGlX53RELYrg91mF8KAsVGFWwGGxfJlp/N+nTrBIphyCeef62NNSsME6wPOFZlfUGYv8QupxGCt8+phzHGRBphKvReQca2S0KnWX0L07kdwmzV7gZia1WTkAcH6HnZOxPY1MYJ9YJTFK75aW+r4VZGsdv2g8PJdMbxJBC83fFanLJ6mqrWvv6umxwCXRnfvhFVUFXiRdh4b2YF8jTX+EJ5ZhbCPb41i1uppzqxpgeIHEQMCJvNNPIikkRXO8SugswtM4BvYqCBVl0tBd7vuQCRw5PGTduoKgPsN+1sF4J1aLYg9hfx/AoWg1RpbqUVzIM0O7GAI49e6WL/2mKq2cE9nF0izxibfWYMLfSsjHAGeR2S7UgN6/5BmVFAVErwkVZTaJt+Z8E63UcGncmBLKIlp/usj+0BuTT4rUBknqeFmi9SSWdxV7ux2AceBCcHa0mXsAf5BJD4R4c1R/YYnrVWrH9iScpsl8x97lgIZs9XCdmSrZ94O90BEJzAPhz9hFgp1ZQzt1RmZs6HtQZVe3agmJvCPzFZ4Yy9lLtbVNeez00vkmpcW4kTMoNpCHZ8y5oo5ASFhxy+En9NjPOAFUSernKEnF7rKmjBpFXXEU0gFTZsx1DOBbfVhh+JPRIoXjc2m0TjS68=
#    file: ./rst/build/geconomicus.zip
#    skip_cleanup: true
#    on:
#      repo: vtexier/Geconomicus
#      tags: true
#      python: '3.4'
